version: '3'

services:
  proxy:    
    image: nginx:latest 
    # this will use the latest version of 1.13.x
    ports:
      - '80:80' 
      # expose 80 on host and sent to 80 in container
    volumes:      
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  
      #:ro indica solo lectura
  web:   
    image: httpd:latest
    build:
      context: .
      dockerfile: Dockerfile
    #reverse server, apache
    #build: .    
    #volumes:      
    #  - .html:/usr/local/apache2/htdocs/
